import {DIMS,PROFILES,QUESTIONS,salaryLabel,RECRUITMENT_GOAL} from './disc.ts';

const esc=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function report(row:any){
 const result=row.result;
 const recruitment=row.goal===RECRUITMENT_GOAL?row.recruitment:null;
 const candidate=recruitment?'<h2 style="font-size:21px;border-top:1px solid #e4eaf1;padding-top:22px">Dados da candidatura</h2><p><b>Telefone / WhatsApp:</b> '+esc(recruitment.phone)+'<br/><b>Cidade / estado:</b> '+esc(recruitment.city)+'<br/><b>Data de nascimento:</b> '+esc(recruitment.birthDate?recruitment.birthDate.split('-').reverse().join('/'):'Não informada')+'<br/><b>Pretensão salarial:</b> '+esc(salaryLabel(recruitment))+'</p>':'';
 const factors=DIMS.map(d=>'<tr><td style="padding:12px;border-bottom:1px solid #e4eaf1"><b>'+d+' · '+PROFILES[d].name+'</b></td><td style="padding:12px;border-bottom:1px solid #e4eaf1;text-align:right">'+result.percentages[d]+'%</td></tr>').join('');
 const details=(result.balanced?DIMS:result.leaders).map((d:keyof typeof PROFILES)=>{const p=PROFILES[d];return '<h3>'+p.name+'</h3><p>'+p.summary+'</p><p><b>Forças:</b> '+p.strength+'</p><p><b>Motivações:</b> '+p.motivation+'</p><p><b>Desenvolvimento:</b> '+p.growth+'</p><p><b>Comunicação:</b> '+p.communication+'</p><p><b>Próximo passo:</b> '+p.action+'</p>';}).join('');
 const choices=row.answers.map((d:string,i:number)=>'<tr><td style="padding:7px;border-bottom:1px solid #eee">'+(i+1)+'</td><td style="padding:7px;border-bottom:1px solid #eee">'+esc(QUESTIONS[i].options.find(o=>o.dimension===d)?.text)+'</td><td style="padding:7px;border-bottom:1px solid #eee">'+esc(d)+'</td></tr>').join('');
 return '<!doctype html><html lang="pt-BR"><body style="background:#f0f3f8;margin:0;padding:24px;font-family:Arial,sans-serif;color:#173661"><div style="max-width:680px;margin:auto;background:#fff"><div style="background:#ffca32;padding:28px"><b style="font-size:24px">MAX IMÓVEIS</b><p style="margin-bottom:0">Perfil comportamental · DISC</p></div><div style="padding:28px;line-height:1.7"><h1 style="font-size:27px">'+esc(row.name)+'</h1><p><b>E-mail:</b> '+esc(row.email)+'<br/><b>Unidade:</b> '+esc(recruitment&&row.unit==='Não se aplica'?'Sem preferência':row.unit)+'<br/><b>Cargo/área:</b> '+esc(row.role)+'<br/><b>Objetivo:</b> '+esc(row.goal)+'<br/><b>Data:</b> '+new Date(row.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})+'</p>'+candidate+'<h2>'+esc(result.title)+'</h2><table style="width:100%;border-collapse:collapse">'+factors+'</table>'+details+'<h3>Respostas registradas</h3><table style="width:100%;border-collapse:collapse;font-size:13px">'+choices+'</table><p style="font-size:12px;color:#627087">Questionário original descritivo inspirado no DISC, sem validação psicométrica. Não constitui diagnóstico ou avaliação psicológica. Use como apoio à conversa; nunca como critério isolado de contratação, promoção ou desligamento. Cada escolha soma 1 ponto; os percentuais são a participação em 40 escolhas. Empates são mantidos. Diferença máxima de 2 pontos entre dimensões é apresentada como tendências próximas.</p><p style="font-size:12px">Registro: '+esc(row.id)+'<br/>Versão: '+esc(row.questionnaire_version)+'<br/>Ciência registrada em '+esc(row.consent_at)+' · '+esc(row.privacy_version)+'</p></div></div></body></html>';
}
